from src.codegen.strategy.write import WriteCgStrat
from src.codegen.strategy.read import ReadCgStrat
from src.codegen.strategy.assign import AssignCgStrat
from src.codegen.strategy.do_while import DoWhileCgStrat
from src.codegen.strategy._while import WhileCgStrat
from src.codegen.strategy.for_down_to import ForDownToCgStrat
from src.codegen.strategy.for_up_to import ForUpToCgStrat
from src.codegen.strategy.if_then import IfThenCgStrat
from src.codegen.strategy.if_then_else import IfThenElseCgStrat